# Generated by Django 5.0.6 on 2024-07-02 23:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Default description', verbose_name='Description'),
        ),
    ]
