# Generated by Django 5.0.6 on 2024-07-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contact_alter_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='message',
        ),
    ]
